### ISSUE TITLE
`1.0.0-rc.1` and `1.0.0-rc.2` are not valid dependencies

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/inx#103]
I am unable to use either of these versions as dependencies. It seems neither was published to crates.io. Also, `1.0.0-rc.2` failed to update the version in `Cargo.toml`.

**Comment by muXxer** [comment]
@Alexandcoats what was the last working version for you?

**Comment by DaughterOfMars** [comment]
`1.0.0-beta.8`

**Comment by muXxer** [comment]
weird, could it be that it was never part of the CI but someone pushed that manually?
Because we never did something different than clicking the "release" button.
Maybe @grtlr pushed that manually?

**Comment by muXxer** [comment]
The changes are not that big :thinking: 
https://github.com/iotaledger/inx/compare/v1.0.0-beta.8...v1.0.0-rc.2

**Comment by DaughterOfMars** [comment]
It is possible he manually published it, I wouldn't know 🤷‍♀️
