### ISSUE TITLE
Rename `minPoWScore` to `minPowScore`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx#78]
@muXxer @alexsporn The later is probably the correct camelCase format of the field.

https://github.com/iotaledger/inx/blob/87419e742c270e227028f97141b03cbc02c54aa2/proto/inx.proto#L63

The current version leads to the following generated Rust code in snake case:

```rust
self.min_po_w_score
```

**Comment by alexsporn** [comment]
It is called `Proof of work (PoW)` (see https://en.wikipedia.org/wiki/Proof_of_work)
Can we add a hint to the Rust generator on how to name that?

**Comment by alexsporn** [comment]
According to the style guide the field names should be in snake_case
https://developers.google.com/protocol-buffers/docs/style
Let me experiment

**Comment by alexsporn** [comment]
I added a Draft PR with this changes. Also note the prefixing of the enum values.

**Comment by grtlr** [comment]
Great–thanks!
