### ISSUE TITLE
Wrap `PendingProtocolParameters::params` into a `RawParameter` type

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx#90]
This would bring it in line with the other raw byte types.

https://github.com/iotaledger/inx/blob/468e350c7410c16242c3f9aade4a9a5c78237848/proto/inx.proto#L72

**Comment by alexsporn** [comment]
Imho it makes no sense, because the bytes cannot be decoded without the other fields in the PendingProtocolParameters
